[package]
name = "rust_websocket_tts"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
ffmpeg-next = "8.0"
r2r = "0.9.5"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3"
